version: "3.5"
services:

  php72_apache:
    build:
      context: "./"
      dockerfile: "./builds/apache/Dockerfile"
    container_name: "php72_apache"
    labels:
      - "traefik.enable=true"                                 # Enable Traefik listener for this service
      - "traefik.backend=php72_apache"                        # Traefik backend service name
      - "traefik.internal.frontend.rule=Host:php72.localhost" # Traefik hostname rule
      - "traefik.port=80"                                     # Traefik front service port
      - "traefik.docker.network=traefik_webgateway"           # Traefik external network,
                                                              # required if you have multiple networks for one service
    volumes:
      - ".:/usr/local/apache2/htdocs/"
    networks:
      - "webgateway"                                          # Apache service is exposed
      - "backend"                                             # Backend is not exposed,
                                                              # but needed to isolate the apache and php communication

  php72_php:
    build:
      context: "./"
      dockerfile: "./builds/php/Dockerfile"
    container_name: "php72_php"
    volumes:
      - ".:/usr/local/apache2/htdocs/"
    depends_on:
      - "php72_apache"
    networks:
      - "backend"                                             # Backend is not exposed,
                                                              # but needed to isolate the apache and php communication

networks:
  backend:
    driver: "bridge"
    name: "php72_backend"                                     # Backend network for this services
  webgateway:
    external:
      name: "traefik_webgateway"                              # External network for exposed service

# docker exec -ti php72_php chmod 777 -R /usr/local/apache2/htdocs/